# Generated by Django 2.1.2 on 2018-10-31 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilePortfolioJunction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(editable=False)),
                ('modified', models.DateField()),
                ('folio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading.Portfolio')),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='stock_folio',
        ),
        migrations.AddField(
            model_name='profileportfoliojunction',
            name='owners',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='stock_folio',
            field=models.ManyToManyField(through='users.ProfilePortfolioJunction', to='trading.Portfolio'),
        ),
    ]
