# Generated by Django 2.1.2 on 2018-10-30 08:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio_name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10, unique=True)),
                ('amount', models.PositiveIntegerField(default=0)),
                ('today_price', models.PositiveIntegerField(default=0)),
                ('company', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='StockPortfolioJunction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(editable=False)),
                ('modified', models.DateField()),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading.Portfolio')),
                ('stocks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading.Stock')),
            ],
        ),
        migrations.CreateModel(
            name='StockPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_date', models.DateField(default=datetime.date.today)),
                ('price_open', models.IntegerField(default=0)),
                ('price_high', models.IntegerField(default=0)),
                ('price_low', models.IntegerField(default=0)),
                ('price_close', models.IntegerField(default=0)),
                ('volume', models.BigIntegerField(default=0)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='trading.Stock')),
            ],
        ),
        migrations.AddField(
            model_name='portfolio',
            name='stock_list',
            field=models.ManyToManyField(through='trading.StockPortfolioJunction', to='trading.Stock'),
        ),
        migrations.AlterUniqueTogether(
            name='stockprice',
            unique_together={('symbol', 'price_date')},
        ),
    ]
